version: '3.8'

services:
  app:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME}:${IMAGE_TAG:-develop-latest}
    container_name: mockexam_app_staging
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - APP_ENV=staging
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE:-mockexam_staging}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - mockexam_staging
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15-alpine
    container_name: mockexam_postgres_staging
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE:-mockexam_staging}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    networks:
      - mockexam_staging
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: mockexam_redis_staging
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ""
    volumes:
      - redis_staging_data:/data
    networks:
      - mockexam_staging
    ports:
      - "6379:6379"

volumes:
  postgres_staging_data:
  redis_staging_data:

networks:
  mockexam_staging:
    driver: bridge