version: '3.8'

services:
  app:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME}:${IMAGE_TAG:-develop-latest}
    container_name: laravel_app_staging
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - APP_ENV=staging
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE:-laravel_staging}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - OCTANE_SERVER=roadrunner
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - laravel_staging
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    container_name: nginx_staging
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/staging.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public:ro
      - ./storage/app/public:/var/www/html/storage/app/public:ro
    networks:
      - laravel_staging
    depends_on:
      - app

  postgres:
    image: postgres:17-alpine
    container_name: postgres_staging
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE:-laravel_staging}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    networks:
      - laravel_staging
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis_staging
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_staging_data:/data
    networks:
      - laravel_staging
    ports:
      - "6379:6379"

  horizon:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME}:${IMAGE_TAG:-develop-latest}
    container_name: horizon_staging
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan horizon
    environment:
      - APP_ENV=staging
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE:-laravel_staging}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
    volumes:
      - ./storage:/var/www/html/storage
    networks:
      - laravel_staging
    depends_on:
      - postgres
      - redis

volumes:
  postgres_staging_data:
  redis_staging_data:

networks:
  laravel_staging:
    driver: bridge