name: Quick Tests

on:
  push:
    branches-ignore: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  quick-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || !contains(github.ref, 'refs/heads/main') && !contains(github.ref, 'refs/heads/develop')

    strategy:
      fail-fast: true
      matrix:
        php: [8.3, 8.4]

    name: Quick Test PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, redis
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-php${{ matrix.php }}-${{ hashFiles('composer.lock') }}
          restore-keys: composer-php${{ matrix.php }}-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --optimize-autoloader

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test

      - name: Execute tests (SQLite)
        run: php artisan test --env=testing